name: MF

on:
  workflow_call:
  workflow_dispatch:


jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunk: [0,1,2,3,4,5,6,7]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper Chunk
        run: python main.py

      - name: Upload Partial Data
        uses: actions/upload-artifact@v6
        with:
          name: chelsea-financial
          path: spreadsheet
          if-no-files-found: error

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Updated: spreadsheet"
 